Models/AnswerImage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lab5.Models
{
    public class AnswerImage
    {

        public int AnswerImageID { get; set; }

        [Required]
        [DisplayName("File Name")]
        public string FileName { get; set; }

        [Required]
        [Url]
        public string Url { get; set; }



    }
}

Controllers/AnswerImagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Azure;
using Azure.Storage.Blobs;
using Lab5.Data;
using Lab5.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lab5.Controllers
{
    public class AnswerImagesController : Controller
    {
        private readonly AnswerImageDataContext _context;
        private readonly BlobServiceClient _blobServiceClient;
        private readonly string containerName = "answerimages";

        public AnswerImagesController(AnswerImageDataContext context, BlobServiceClient blobServiceClient)
        {
            _context = context;
            _blobServiceClient = blobServiceClient;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.AnswerImages.ToListAsync());
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile answerImage)
        {
            BlobContainerClient containerClient; // instanciate a class to allow us to manipulate the blob storage we made

            try
            {
                // Attempt to create a new container that will hold our blob images if it already exists we'll get a RequestFailedException
                containerClient = await _blobServiceClient.CreateBlobContainerAsync(containerName); 
                // Set the access to the container to be public allowing anyone to upload images to our blob container
                containerClient.SetAccessPolicy(Azure.Storage.Blobs.Models.PublicAccessType.BlobContainer);
            } catch(RequestFailedException)
            {
                // We've already made a blob container, continue with the old blob container.
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }

            try
            {
                // create the blob to hold the data
                var blockBlob = containerClient.GetBlobClient(answerImage.FileName);

                // check if the blob already exists
                if (await blockBlob.ExistsAsync())
                {
                    // if so lets delete it.
                    await blockBlob.DeleteAsync();
                }

                // get a new memory stream so we can upload to the storage container.
                using (var memoryStream = new MemoryStream())
                {
                    // copy the file data into memory
                    await answerImage.CopyToAsync(memoryStream);

                    // navigate back to the beginning of the memory stream
                    memoryStream.Position = 0;

                    // send the file to the cloud
                    await blockBlob.UploadAsync(memoryStream);
                    memoryStream.Close();
                }

                // add the photo to the database if it uploaded successfully.
                var image = new AnswerImage();
                image.Url = blockBlob.Uri.AbsoluteUri;
                image.FileName = answerImage.FileName;

                // add it to our array of answer images in our AnswerImageDataContext
                _context.AnswerImages.Add(image);
                // update our data in the database with the new data added above.
                _context.SaveChanges();
            }
            catch (RequestFailedException)
            {
                // if the image fails to upload to our storage.
                View("Error");
            }
            // return to our index view.
            return RedirectToAction("Index");


        }


        public async Task<IActionResult> Delete(int? id)
        {
            // User error checking to see if there actually is an id
            if (id == null)
            {
                return NotFound();
            }
            // find the image in our database
            var image = await _context.AnswerImages
                .FirstOrDefaultAsync(m => m.AnswerImageID == id);
            // User error checking to see if a user maliciously sends in an id that doesn't exist in our database
            // or if two users try to delete the image at the same time.
            if (image == null)
            {
                return NotFound();
            }
            // Send the image to the view for display.
            return View(image);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var image = await _context.AnswerImages.FindAsync(id);


            BlobContainerClient containerClient;
            // Get the container for our blobs, if failure go to Error view.
            try
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            try
            {
                // Get the blob that holds the data
                var blockBlob = containerClient.GetBlobClient(image.FileName);

                // Check if the blob exists
                if (await blockBlob.ExistsAsync())
                {
                    // if the blob already exists delete it.
                    await blockBlob.DeleteAsync();
                }
                // Remove the image from our database
                _context.AnswerImages.Remove(image);
                // Save our changes
                await _context.SaveChangesAsync();

            }
            catch (RequestFailedException)
            {
                return View("Error");
            }
            // Go back to the index.
            return RedirectToAction("Index");
        }

    }

}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Lab5.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/AnswerImages/Delete.cshtml
@model AnswerImage

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Answer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt class="col-sm-2">
            Image
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.Url" style="max-width: 400px;" />
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="AnswerImageID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/AnswerImages/Index.cshtml
@model IEnumerable<AnswerImage>

<h1>Index</h1>
<p>
    <a asp-action="Upload">Upload New</a>
</p>

@if (Model.Count() == 0)
{
    <p>There are no files to display.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FileName)
                </th>
                <th>
                    Image
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileName)
                    </td>
                    <td>
                        <img src="@item.Url" style="max-width: 400px;" />
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@item.AnswerImageID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/AnswerImages/Upload.cshtml
@{
    ViewData["Title"] = "Upload";
}

<h1>Upload</h1>

<h4>Upload a smiley face</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Upload" enctype="multipart/form-data">
            <div class="form-group">
                <div class="btn btn-sm float-left">
                    <input name="answerImage" type="file">
                </div>
            </div>

            <div class="form-group">
                <button type="submit" name="upload" class="btn btn-primary">Upload Now</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Index.cshtml
<div class="container">
    <main role="main" class="pb-3">

        <div class="text-center">
            <h1 class="display-4">Welcome</h1>
            <p>Hey my name is Amero Defranco and I like programming I guess</p>
        </div>

    </main>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Home Page - Lab5</title>
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/site.css">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" href="/">Lab5</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="AnswerImages" asp-action="Index">Answers</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div>
            @RenderBody()
        </div>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>